### ISSUE TITLE
Low time complexity random access

### ISSUE THREAD

**Issue by alion02** [aaronjanse/asciidots#73]
I wanted to work on a project that would benefit from low time complexity random access of an array. O(1) would be preferable, but O(log n) should suffice.

- There is no language-defined character that allows this.
- Simulating an array via the queue-like behavior of operation cells is unacceptable because of O(n) random access.
- I tried to define a recursive library that would simulate an array-like structure via trees with O(log n) random access time complexity, but libraries are pre-loaded recursively and that, understandably, makes Python complain about the max recursion depth being reached immediately after attempting to start the program.
- Expanding the libraries manually is unacceptable because the resulting code size would be absurd.

And with that I'm stuck. One solution I came up with is to allow for lazy-loading of libraries (only load a library when the first dot enters its character), which would make a recursive library possible.

Here's a minimal snippet that shows what I'd like to achieve.

recursive_library.dots:
```
%!recursive_library.dots L
%!recursive_library.dots R
%^X

 /L
X~R
```

This code currently crashes the interpreter with a `RecursionError`, even though `L` and `R` are provably unused.

**Comment by aaronduino** [comment]
Hmm, that is an interesting situation. That is correct that library recursion is not natively supported.

> I tried to define a recursive library that would simulate an array-like structure via trees with O(log n) random access time complexity

Perhaps there is a different way to go about doing this?

If the array in question is fixed in size, you could create a base memory cell library and connect them in a fixed-depth tree of libraries.

Psuedocode:
main file:
```
%!tree.dots A

A
``` 

tree.dots:
```
%!tree1.dots A

AAAA
``` 

tree1.dots:
```
%!tree2.dots A

AAAA
``` 

tree2.dots:
```
%!tree3.dots A

AAAA
``` 

tree3.dots:
```
`` memory cell code
``` 

---

P.S. sorry that I've not been very responsively recently. I have been triaging linux distros and haven't had a stable development environment. Tomorrow, I'll be able to do some real work on resolving the bugs you reported.

**Comment by alion02** [comment]
The program will have access to the desired array size at runtime, and it may be massive so I'd prefer to not do any hard-coded solutions. I will also look into other, domain-specific methods of handling this - perhaps they will prove to be sufficient.

**Comment by alion02** [comment]
Even still, a lack of an O(1) random access structure is annoying. I don't think `,` is used for anything - perhaps simply make it an array?

**Comment by aaronduino** [comment]
> I don't think `,` is used for anything - perhaps simply make it an array?

I'd like to keep the language minimal; I'm already starting to regret the complexity added by libraries and warps (but of course it's too late to do anything about those two—they're here to stay)

Hmmm, I think that no matter what ends up happening you are going to have to have a finite number of tildes (`~`) for storage. So it's just a matter of how many (note that you could have 20 of them and then have each store an unbounded number of dots if you have a clever enough indexing system)
