### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by Brent-Trenholme** [aaronjanse/asciidots#85]
I ran this code with the interpreter
.-#42-$#-&
and got this output
failed to import curses; running in compatibility mode
42
I used this command
python __main__.py ../ree.dots
How do I fix the compatibility issue? I've looked around and found nothing

**Comment by Brent-Trenholme** [comment]
I've found a solution:
python -m pip install windows-curses
I was on windows, maybe add it to the installation instructions?

**Comment by aaronjanse** [comment]
>  I was on windows, maybe add it to the installation instructions?

Would you mind making a PR? I'd love to add it to the instructions.

**Comment by Brent-Trenholme** [comment]
ok

**Comment by Brent-Trenholme** [comment]
took me a while since it was my first ever pull request but it's done

**Comment by aaronjanse** [comment]
Thank you! Feel free to open another issue if you have any more questions.
