### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by jakiki6** [aaronjanse/asciidots#87]
You could add a "§" as an oberver. An observer does output a signal if a connected item changed. All items which are affected by this signal doesn't trigger the observer.  

Example:

`.\`
`(<)`
`§------$'Hello world!'`

**Comment by aaronjanse** [comment]
Hmm, what would be the use case over modifying the code to use an asterisk duplicator?

```
/v-.
\*---$'Hello world!'
```
