### ISSUE TITLE
Backend stopped working

### ISSUE THREAD

**Issue by Asapros** [aaronjanse/asciidots#92]
I have recently tested on the website a program that keeps multiplying a dot value by itself, after reaching a very high number, the backend crashed. (It wasn't my goal, please forgive me) If it is a coincidence, take this as a normal report of not working servers. (Now like 15 minutes passed, it's still not working)

Ok now it's fixed (10pm CET)

![image](https://user-images.githubusercontent.com/75039747/119558869-4252b400-bda2-11eb-9f67-ba8fe62d04ab.png)

**Comment by aaronjanse** [comment]
Hello! I got an email from Heroku saying that I'm near my limit for free hours this month. That's totally fine—it doesn't cost me anything—but that's probably why the backend would be down. I got this yesterday, so the issue most likely wasn't your program.

You might want to try out https://tio.run :-)

Enjoy asciidots!
